#!/bin/sh

cat <<EOF >tmp.tex
\input manmac \relax
\font\myfont=$1
\beginchart\myfont
\normalchart
\endchart
\bye
EOF
if pdftex tmp.tex; then
	rm -f tmp.tex tmp.log answers.tex index.tex
	xdg-open tmp.pdf
fi
