#!/bin/sh

cat <<EOF >tmp.tex
\input manmac \relax
\font\myfont=$1
\beginchart\myfont
\normalchart
\endchart
\bye
EOF
pdftex tmp.tex && xdg-open tmp.pdf
rm -f tmp.tex tmp.log answers.tex index.tex missfont.log
